swagger: "2.0"
info:
 
  version: "1.0.0"
  title: "User Management"
  
host: "localhost:4000/api"
basePath: "/um"
tags:
- name: "User Management"
  
schemes:
- "http"
paths:
 
  /register:
    post:
      tags:
      - "User Management"
      summary: "Create new User"
      description: "Register a new user in the system"
      operationId: "RegisterUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object to create new user"
        required: true
        schema:
          $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "New User Registered Successfully"
        400:
          description: "Invalid Request Data"
  /login:
    post:
      tags:
      - "User Management"
      summary: "Login in to App"
      description: "Login with already existing user details"
      operationId: "LoginUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Registration user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successfull Login with jwt token"
        400:
          description: "Invalid Request Data"
  
definitions:
  NewUser:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phoneNumber:
        type: "string"
    xml:
      name: "User"
  User:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
  